### ISSUE TITLE
Failed to build without libpcre

### ISSUE THREAD

**Issue by yakimant** [status-im/nim-dnsdisc#15]
Looks like if it's not installed, build is failing:
```
/usr/bin/ld: cannot find -lpcre: No such file or directory
```

Luckily I've found a key in https://github.com/status-im/nimbus-build-system, so this works: `make creator LINK_PCRE=0`

Maybe we should set it in Makefile or document the requirements in tutorial.

**Comment by jakubgs** [comment]
Added Nix shell that provides PCRE in:

* https://github.com/status-im/nim-dnsdisc/pull/16
